api_platform:
    allow_plain_identifiers: true
    title: API Platform
    version: 1.0.0
    show_webby: false
    enable_profiler: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure:
        enabled: false
#        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    # Good defaults value for REST APIs
    defaults:
        stateless: true
        # Good cache defaults
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            page_parameter_name: 'page'
            items_per_page_parameter_name: 'pageSize'
            enabled: true
            partial: false
    formats:
        json:
            mime_types: [ 'application/json' ]
    # Enable the entrypoint.
    enable_entrypoint: true
