apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name | quote }}
  {{- if (.Values.mysqlfeature) }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
  {{- end }}
spec:
{{- if (.Values.mysqlfeature) }}
  type: NodePort
{{ else }}
  type: ClusterIP
{{- end }}
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.mysql.name | quote }}
subsets:
  - addresses:
      - ip: {{ .Values.mysql.ip }}
    ports:
      - port: {{ .Values.mysql.port }}
